### ISSUE TITLE
hi, 你的帳密沒有碼掉喔

### ISSUE THREAD

**Issue by DCTmaybe1201** [vi000246/EynyMegaDownloader#2]
伊莉那個的config裡面

**Comment by vi000246** [comment]
thanks

**Comment by ronsun** [comment]
只改掉密碼還是可以從 commit 追出來，要想辦法把之前的 commit 處理掉或整個 repository 重建

**Comment by vi000246** [comment]
其實我已經改掉帳密了，所以就直接移除密碼而已
剛剛參考這篇把歷史紀錄也刪掉了
https://is.gd/yoi4WY
感謝你的提醒
